name: Semgrep Security Scan
on:
  pull_request:
  push:
    branches: [main]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: |
        semgrep scan \
          --config p/security-audit \
          --config ./semgrep/custom-rules \
          --sarif \
          --output semgrep.sarif
    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: semgrep.sarif